config/routes.rb
Rails.application.routes.draw do
  resources :t_reg_codes, only:[:new, :create]
  resources :t_users
  root to: "t_users#index"
end

app/models/t_reg_code.rb
class TRegCode < ActiveRecord::Base
  # relation
  belongs_to :t_user
end

app/models/t_user.rb
class TUser < ActiveRecord::Base
  # validation
  validates :f_lastname, presence: true
  validates :f_firstname, presence: true
  validates :f_birthday, presence: true
  validates :f_mail, presence: true
  validates :f_country_id, presence: true
  validates :f_language_id, presence: true
  validates :f_login_flg, presence: true
  validates :f_sex, presence: true
  validates :f_auth_flg, presence: true

  #relation
  has_many :t_reg_codes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/t_reg_codes_controller.rb
class TRegCodesController < ApplicationController
  def new
    @code = TRegCode.new
  end

  def create
    @code = TRegCode.new(code_params)

    if @code.save
      # binding.pry
      redirect_to t_user_path(@code.f_user_id), success: 'QRコードの発行が完了しました'
    else
      @user = TUser.find_by(id: @code.id)
      flash.now[:error] = 'エラーによりQRコードの発行ができませんでした'
      render 't_users/show'
    end
  end

  private
  def code_params
    params.permit(:f_code, :f_user_id, :f_val_date, :f_inval_date)
  end
end

app/controllers/t_users_controller.rb
class TUsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = TUser.all.reverse_order
  end

  def show
    @codes = TRegCode.where(f_user_id: @user.f_user_id)
  end

  def new
    @user = TUser.new
  end

  def create
    @user = TUser.new(user_params)
    if @user.save
      redirect_to t_user_path(@user), success: "#{@user.f_lastname + " " + @user.f_firstname} 様の登録が完了しました"
    else
      render 'new', error: "エラーが発生しています"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), success: "ユーザー情報を変更しました"
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, success: "#{@user.f_lastname + @user.f_firstname}様を削除しました"
  end


  private
  def set_user
    @user = TUser.find(params[:id])
  end

  def user_params
    params.require(:t_user).permit(:f_user_id, :f_lastname, :f_firstname, :f_birthday, :f_mail, :f_country_id, :f_language_id, :f_login_flg, :f_sex, :f_comment, :f_auth_flg)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def qrcode_tag(text, options = {})
      qr = ::RQRCode::QRCode.new(('sample_url/' + text))
   return ChunkyPNG::Image.from_datastream(qr.as_png.resize(300,300).to_datastream).to_data_url
  end
end

app/helpers/t_reg_codes_helper.rb
module TRegCodesHelper
end

app/helpers/t_users_helper.rb
module TUsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SangakuRenkei2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/t_users/_t_user_form.html.erb
<p class="notification">Find me in app/views/t_users/_t_user_form.html.erb</p>

<%= form_for(@user) do |f| %>
  <!--名-->
  <%= f.label :'名前(lastname)' %><br>
  <%= f.text_field :f_lastname, class: "base-input" %><br>
  <!--姓-->
  <%= f.label :'苗字(firstname)' %><br>
  <%= f.text_field :f_firstname, class: "base-input" %><br>
  <!--生年月日-->
  <%= f.label :'生年月日' %><br>
  <%= raw sprintf(
      f.date_select(
        :f_birthday,
        use_month_numbers: true,
        start_year: (Time.now.year - 100),
        end_year: (Time.now.year - 10),
        default: Date.new((Time.now.year - 30), 1, 1),
        date_separator: '%s'),
      '年 ', '月',) + '日'
  %><br>
  <!--メールアドレス-->
  <%= f.label :'メールアドレス' %><br>
  <%= f.email_field :f_mail, class: "base-input" %><br>
  <!--国-->
  <%= f.label :'出身国' %><br>
  <%# f.collection_select  :f_country_id, TCountry.all, :id, :name %>
  <%= f.number_field :f_country_id, class: "base-input" %><br>
  <!--言語-->
  <%= f.label :'言語' %><br>
  <%# f.collection_select  :f_language_id, TLanguage.all, :id, :name %>
  <%= f.number_field :f_language_id, class: "base-input" %><br>
  <!--ログイン種別-->
  <%= f.label :'ログイン種別' %><br>
  <%= f.select :f_login_flg, [["種別1", 0], ["種別2", 1], ["種別3", 2]], class: 'form-control' %><br>
  <!--性別-->
  <%= f.label :'性別' %><br>
  <%= f.select :f_sex, [["男", "男"], ["女", "女"]], class: 'form-control' %><br>
  <!--公認フラグ-->
  <%= f.label :'公認フラグ' %><br>
  <%= f.select :f_auth_flg, [["非公認", 0],["公認", 1]], class: 'form-control' %><br>
  <!--一言コメント-->
  <%= f.label :'一言コメント' %><br>
  <%= f.text_area :f_comment %><br>

  <%= f.submit %><br>

  <% end %>

app/views/t_users/edit.html.erb
<header class="c-header">
  <h1 class="c-header__title">TUsers#edit</h1>
  <%= link_to 'ユーザー覧へ', t_users_path, class: "c-header__link" %>
  <%= link_to  "ユーザーの新規登録", new_t_user_path, class: "link-button" %>
</header>
<main class="c-main">
<p>Find me in app/views/t_users/edit.html.erb</p>

<%= render 't_user_form' %>

</main>

app/views/t_users/index.html.erb
<header class="c-header">
  <h1 class="c-header__title">TUsers#index</h1>
  <%= link_to 'ユーザー覧へ', t_users_path, class: "c-header__link" %>
  <%= link_to  "ユーザーの新規登録", new_t_user_path, class: "link-button" %>
</header>
<main class="c-main">
<p class="notification">Find me in app/views/t_users/index.html.erb</p>

<p class="c-main__title">ユーザー一覧</p>
<% unless @users.blank? %>
  <!--ユーザーが存在する場合-->
  <table>
    <tr>
      <th>No</th>
      <th>名前</th>
      <th>生年月日</th>
      <th>メールアドレス</th>
      <th>国</th>
      <th>言語</th>
      <th>ログイン種別</th>
      <th>性別</th>
      <th>自治体公認</th>
      <th>一言コメント</th>
      <th>登録日</th>
      <th>更新日</th>
      <th>詳細</th>
    </tr>
    <% @users.each do |user|%>
      <tr>
        <!--No-->
        <td><%= user.f_user_id %></td>
        <!--名前-->
        <td><%= user.f_lastname %> <%= user.f_firstname %></td>
        <!--生年月日-->
        <td><%= user.f_birthday %></td>
        <!--メールアドレス-->
        <td><%= user.f_mail %></td>
        <!--国-->
        <td><%= user.f_country_id %></td>
        <!--言語-->
        <td><%= user.f_language_id %></td>
        <!--ログイン種別-->
        <td><%= user.f_login_flg %></td>
        <!--性別-->
        <td><%= user.f_sex %></td>
        <!--自治体公認フラグ-->
        <td><%= user.f_auth_flg %></td>
        <!--一言コメント-->
        <td><%= user.f_comment %></td>
        <!--登録日時-->
        <td><%= user.f_reg_date %></td>
        <!--更新日時-->
        <td><%= user.f_upd_date %></td>
        <td><%= link_to '詳細', t_user_path(user.f_user_id), class: "link-button" %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <!--ユーザーが存在しない場合-->
  <p>まだユーザーは存在しません</p>
<% end %>
</main>

app/views/t_users/new.html.erb
<header class="c-header">
  <h1 class="c-header__title">TUsers#new</h1>
  <%= link_to 'ユーザー覧へ', t_users_path, class: "c-header__link" %>
  <%= link_to  "ユーザーの新規登録", new_t_user_path, class: "link-button" %>
</header>
<main class="c-main">
<p class="notification">Find me in app/views/t_users/new.html.erb</p>


<%= render 't_user_form' %>


</main>

app/views/t_users/show.html.erb
<header class="c-header">
  <h1 class="c-header__title">TUsers#show</h1>
  <%= link_to 'ユーザー覧へ', t_users_path, class: "c-header__link" %>
  <%= link_to  "ユーザーの新規登録", new_t_user_path, class: "link-button" %>
</header>
<main class="c-main">
<p class="notification">Find me in app/views/t_users/show.html.erb</p>
  <!--名-->
  <label>名前(lastname)</label><br>
  <%= @user.f_lastname %><br>
  <!--姓-->
  <label>苗字(firstname)</label><br>
  <%= @user.f_firstname %><br>

  <!--生年月日-->
  <label>生年月日</label><br>
  <%= @user.f_birthday %><br>
  <!--メールアドレス-->
  <label>メールアドレス</label><br>
  <%= @user.f_mail %><br>

  <!--国-->
  <label>出身国</label><br>
  <%= @user.f_country_id %><br>

  <!--言語-->
  <label>言語</label><br>
  <%= @user.f_language_id %><br>

  <!--ログイン種別-->
  <label>ログイン種別</label><br>
  <%= @user.f_login_flg %><br>

  <!--性別-->
  <label>性別</label><br>
  <%= @user.f_sex %><br>

  <!--公認フラグ-->
  <label>公認フラグ</label><br>
  <%= @user.f_auth_flg %><br>

  <!--一言コメント-->
  <label>一言コメント</label><br>
  <%= @user.f_comment %><br>

  <label>QRコード</label>
  <% unless @codes.blank? %>
    <% @codes.each do |code| %>
    <%= image_tag qrcode_tag(code.f_code) %>
    <% end %>
  <% else %>
    <p>まだ発行されていません</p>
  <% end %>

  <p><%= link_to '情報の修正', edit_t_user_path(@user.id), class: 'link-button' %></p>

<% @uuid = SecureRandom.uuid %>
<% @now = Time.current %>

<%= form_tag(t_reg_codes_path) do |f| %>
  <!-- コード -->
  <%= hidden_field_tag :f_code, @uuid %>
  <!-- ユーザーID -->
  <%= hidden_field_tag :f_user_id, @user.f_user_id %>
  <!-- 発行日時 -->
  <%= hidden_field_tag :f_val_date, @now %>
  <!-- 失効日時 -->
  <%= hidden_field_tag :f_inval_date, @now.since(7.days) %>
  <%= submit_tag 'QRコードを発行' %>
<% end %>
</main>